### ISSUE TITLE
ERROR: duplicate Class found: 'Document'

### ISSUE THREAD

**Issue by iTerentius** [scztt/LanguageServer.quark#12]
With the LanguageServer quark installed I get this error. 

ERROR: duplicate Class found: 'Document' 
/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary/scide_scqt/ScIDE.sc
/Users/isaaclinder/Library/Application Support/SuperCollider/downloaded-quarks/LanguageServer/LSPDocument.sc

This happens in SCIDE as well with the extension. Without it the server boots fine (but obviously doesn't work with VSCode at that point).

**Comment by iTerentius** [comment]
Disregard that. Sorry, Dev release of SC needed.

**Comment by iTerentius** [comment]
Disregard that. Sorry, Dev release of SC needed.

**Comment by iTerentius** [comment]
Sorry, actually still doesn't work. Maybe something with my setup but don't know yet.

**Comment by scztt** [comment]
Are you running SuperCollider in VSCode or using the regular SuperCollider IDE? For the time being, the Language Server quark isn't supported in the regular IDE - actually due to this specific issue. This will be cleaned up eventually, but for the time being I would suggest enabling the LanguageServer quark only if you're using VSCode.

**Comment by iTerentius** [comment]
I am only use SCIDE to determine the issue with VSCode. In VSCode I get SC syntax highlighting. Using the command palette to boot the server shows it start for a quick second and then closes with no output in VSCode. It's likely something with my setup. As a note I have it working on Linux for the most part other than no sound from executed SC code, but I do get it with TidalCycles, so I don't believe it's audio - but that's why I was trying on a mac.
