### ISSUE TITLE
String should be a symbol

### ISSUE THREAD

**Issue by spluta** [scztt/LanguageServer.quark#24]
In this line:

https://github.com/scztt/LanguageServer.quark/blob/2d4935ecfa41c1031db2e4f3cb64d4d68b3d98da/Providers/SignatureHelpProvider.sc#L92

I believe:

Log("LanguageServer.quark").info("Finding method name before %", end);

should be:

Log('LanguageServer.quark').info("Finding method name before %", end);

It is formatted as a symbol everywhere else in the code set and this removes and error that is posted every time there is an open parenthesis.

**Comment by scztt** [comment]
thanks for noticing this - resolved.
