### ISSUE TITLE
Undefined classes

### ISSUE THREAD

**Issue by davidgranstrom** [scztt/LanguageServer.quark#6]
The following classes are undefined for me (I guess they might be part of a quark?)

* `NdefPreset`
* `PdefPreset`
* `TdefPreset`

https://github.com/scztt/LanguageServer.quark/blob/develop/CompletionHandlers/LSPCompletionHandler_singleton.sc#L83

I've commented these lines out in my local clone for now, but maybe they could removed and instead be extended in their source files instead?

**Comment by scztt** [comment]
I'll remove these, I didn't notice they were not part of the core lib.
